const express=require('express')
const router = express.Router()
const doctorController=require('../controller/doctor/doctorController')
router.post('/login',doctorController.doctorLogin)
router.get('/getDoctor',doctorController.singleDoctor)
router.patch('/changePassword', doctorController.changePassword)
router.get('/getSingleBooking/:id',doctorController.getSingleBooking)
router.get('/getBookings',doctorController.getBookings)
router.post('/prescription',doctorController.prescriptionAdding)
router.get('/getPrescription/:id',doctorController.getPrescription)
router.get('/getClients',doctorController.getClients)
router.get('/getAllBookings',doctorController.getAllBookings)
router.get('/cancelbooking/:id',doctorController.cancelbooking)
router.get('/blockclient/:id',doctorController.blockClient)
module.exports = router